
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64" # Utilizza l'immagine Ubuntu 22.04 LTS (Jammy Jellyfish)


  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntuLivioIsTheBest"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.11" # Imposta un indirizzo IP privato per la VM
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Mappa la porta 8080 della VM alla porta 8080 dell'host

  #Aggiornamenti generali del sistema
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y
  SHELL

  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "main.yml" 
  end

end
