
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64" # Utilizza l'immagine Ubuntu 22.04 LTS (Jammy Jellyfish)


  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntuLivioIsTheBest"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.11" # Imposta un indirizzo IP privato per la VM
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Mappa la porta 8080 della VM alla porta 8080 dell'host

  #Aggiornamenti generali del sistema
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y
  SHELL
  #############################################################################
  # Decommentare le righe seguenti per eseguire i playbook Ansible specifici
  #############################################################################
  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "install_helm.yml"
  # end

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "install_docker.yml"
  # end

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "install_kind.yml"
  # end

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "install_jenkins.yml"
  # end

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "install_kubectl.yml"
  # end

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "configure_jenkins_kube.yml"
  # end

  # Playbook principale che include tutti gli altri
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "main.yml" # main.yml è il playbook principale che include tutti gli altri
  end

end
