- name: Configure limits for user in /etc/security/limits.conf
  hosts: localhost
  become: true
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - name: Generate temporary file from template
      template:
        src: templates/limits.j2
        dest: /tmp/limits_{{ utente }}.txt

    - name: Insert limits into the /etc/security/limits.conf file
      blockinfile:
        path: /etc/security/limits.conf
        marker: "# {mark} ANSIBLE LIMITS {{ utente }}"
        block: "{{ lookup('file', '/tmp/limits_' + utente + '.txt') }}"