- become: true
  hosts: all
  name: Provisioning completo Jenkins + Docker
  tasks:
  - dnf:
      name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      state: absent
    name: Disinstalla eventuali versioni vecchie
  - dnf:
      name:
      - dnf-plugins-core
      state: present
    name: Installa pacchetti richiesti
  - args:
      creates: /etc/yum.repos.d/docker-ce.repo
    command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    name: Aggiungi il repository Docker ufficiale
  - dnf:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: latest
    name: Installa Docker Engine
  - name: Abilita e avvia il servizio Docker
    systemd:
      enabled: true
      name: docker
      state: started
  - dnf:
      name:
      - python3
      - python3-pip
      state: present
    name: Installa python3 e pip3
  - name: Installa il modulo docker di Python
    pip:
      executable: pip3
      name: docker
  - community.docker.docker_network:
      driver: bridge
      ipam_config:
      - subnet: 192.168.100.0/24
      name: mia_rete
    name: Crea una Docker network chiamata "mia_rete"
  - dnf:
      name: podman-docker
      state: absent
    name: Rimuovi podman-docker se presente (evita conflitto)
  - dnf:
      name:
      - python3
      - python3-pip
      - dnf-plugins-core
      state: present
    name: Installa pacchetti base (Python, pip, plugin DNF)
  - args:
      creates: /etc/yum.repos.d/docker-ce.repo
    command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    name: Aggiungi il repository ufficiale di Docker
  - dnf:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
    name: Installa Docker CE
  - name: Abilita e avvia il servizio Docker
    systemd:
      enabled: true
      name: docker
      state: started
  - name: Installa il modulo Python per Docker
    pip:
      executable: pip3
      name: docker
  - community.docker.docker_network:
      driver: bridge
      ipam_config:
      - subnet: '{{ jenkins_subnet }}'
      name: '{{ jenkins_network }}'
    name: Crea rete Docker Jenkins
  - community.docker.docker_container:
      image: jenkins/jenkins:lts
      name: '{{ jenkins_container_name }}'
      networks:
      - ipv4_address: '{{ jenkins_ip }}'
        name: '{{ jenkins_network }}'
      ports:
      - 8080:8080
      - 50000:50000
      restart_policy: always
      state: started
      volumes:
      - jenkins_home:/var/jenkins_home
    name: Esegui container Jenkins (solo master)
  - community.docker.docker_network:
      name: '{{ jenkins_network }}'
      state: present
    name: Assicurati che la rete Docker esista
  - community.docker.docker_container:
      command: []
      env:
        JENKINS_AGENT_NAME: '{{ jenkins_agent_name }}'
        JENKINS_AGENT_WORKDIR: '{{ jenkins_agent_workdir }}'
        JENKINS_SECRET: '{{ jenkins_agent_secret }}'
        JENKINS_URL: '{{ jenkins_master_url }}'
      image: '{{ jenkins_agent_image }}'
      name: '{{ jenkins_agent_container }}'
      networks:
      - name: '{{ jenkins_network }}'
      privileged: true
      recreate: true
      restart_policy: always
      state: started
    name: Avvia container Jenkins Agent
  - community.docker.docker_container_exec:
      command: apt-get update
      container: jenkins-agent
      tty: true
      user: root
    name: Aggiorna la cache dei pacchetti dentro Jenkins Agent
  - community.docker.docker_container_exec:
      command: apt-get install -y docker.io
      container: jenkins-agent
      tty: true
      user: root
    name: Installa Docker CLI nel container Jenkins Agent
  vars:
    jenkins_agent_container: jenkins-agent
    jenkins_agent_image: jenkins/inbound-agent:latest
    jenkins_agent_name: agent
    jenkins_agent_secret: 678ea4e6ba0a85dac5ec2148e4284150eca5942e76786d8e1409aab51b75731d
    jenkins_agent_workdir: /home/jenkins/agent
    jenkins_container_name: jenkins-master
    jenkins_ip: 172.30.0.10
    jenkins_master_url: http://172.30.0.10:8080
    jenkins_network: jenkins_net
    jenkins_subnet: 172.30.0.0/16
