Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.hostname = "rocky-vm"

  # Rete privata + forwarding porta Jenkins
  config.vm.network "private_network", ip: "192.168.56.25"
  config.vm.network "forwarded_port", guest: 8080, host: 8080  # Usa 8081 per evitare conflitti

  # Risorse VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "rocky-docker-vm"
    vb.memory = 2048
    vb.cpus = 2
  end

  # Provisioning con un unico playbook Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main_playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
