Vagrant.configure("2") do |config|
  # Specify the base box to use, in this case Rocky Linux 9
  config.vm.box = "rockylinux/9"
  
  # Set the hostname of the virtual machine
  config.vm.hostname = "rocky-vm"

  # Network configuration:
  # - "private_network" creates a private network accessible from the host via IP
  # - Static IP assigned to the VM
  config.vm.network "private_network", ip: "192.168.56.25"

  # Port forwarding:
  # - Exposes port 8080 of the VM (guest) to port 8080 on the host
  # - Useful for accessing Jenkins from the host's browser
  config.vm.network "forwarded_port", guest: 8080, host: 8080  

  # VM resource configuration using VirtualBox
  config.vm.provider "virtualbox" do |vb|
    # Name assigned to the virtual machine in VirtualBox
    vb.name = "rocky-docker-vm"
    
    # Amount of RAM allocated to the VM (in MB)
    vb.memory = 2048
    
    # Number of CPU cores allocated to the VM
    vb.cpus = 2
  end

  # Automatic provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    # Name of the Ansible playbook to run to configure the VM
    ansible.playbook = "main_playbook.yml"
    
    # Set compatibility mode to Ansible version 2.0
    ansible.compatibility_mode = "2.0"
  end
end
