# Questo blocco viene eseguito solo se la creazione del ServiceAccount è abilitata nel values.yaml
{{- if .Values.serviceAccount.create -}}

# Versione dell'API Kubernetes per il ServiceAccount
apiVersion: v1

# Tipo di risorsa
kind: ServiceAccount

metadata:
  # Nome del ServiceAccount generato dinamicamente
  name: {{ include "flask-app.serviceAccountName" . }}

  # Etichette applicate all'oggetto, utili per selezione o organizzazione
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}

  # Se sono presenti annotazioni definite nei values, vengono incluse qui
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

# Specifica se il token del ServiceAccount deve essere automaticamente montato nei pod
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

# Fine del blocco condizionale
{{- end }}