apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: busybox # nome del container
    image: busybox # immagine del container
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/nfs # path dove il volume NFS sarà montato nel container
  volumes:
  - name: nfs-volume # NFS volume definizione
    nfs:
      server: 192.168.56.10 # ip del NFS server
      path: /srv/nfs/kshare # path del NFS share
      readOnly: false
