apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html # Percorso nel container dove il volume sarà montato
      name: nfs-volume # Nome del volume che verrà montato nel container
  volumes:
  - name: nfs-volume # Nome del volume che verrà montato nel container
    persistentVolumeClaim:
      claimName: nfs-pvc # Nome del PVC creato in nfs-pvc.yaml
