apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: ""         # <-- Disabilita la richiesta implicita di StorageClass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
