apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: ""       # Specifica che non si utilizza una StorageClass
  accessModes:
    - ReadWriteMany # Modalità di accesso
  resources:
    requests:
      storage: 5Gi # Dimensione richiesta del PVC
