- name: Install or remove packages based on dictionary     
  hosts: localhost                                         
  become: true                                             
  vars:                                                    
    packages:                                              
      vim: present                                        
      nano: absent                                         
      git: present                                         

  tasks:                                                   
    - name: Ensure packages are in desired state           
      ansible.builtin.package:                             
        name: "{{ item.key }}"                             
        state: "{{ item.value }}"                          
      loop: "{{ packages | dict2items }}"                  
                                                           
