---
- name: Create users from a list of dictionaries
  hosts: localhost
  become: true

  vars:
    users:
      - name: alice
        group: dev
        home: /home/alice
        shell: /bin/bash
      - name: matteo
        group: ops
        home: /home/matteo
        shell: /bin/zsh

  tasks:
    - name: Ensure groups exist
      ansible.builtin.group:
        name: "{{ item.group }}"
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.group }}"

    - name: Ensure users are created with correct properties
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        home: "{{ item.home }}"
        shell: "{{ item.shell }}"
        state: present
        create_home: yes
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
