FROM {{ base_image }}

{% if extra_packages %}
RUN apt-get update && apt-get install -y \
    {% for pkg in extra_packages %}
    {{ pkg }}{% if not loop.last %} \{% endif %}
    {% endfor %}
{% endif %}

COPY default.conf /etc/nginx/conf.d/default.conf

CMD {{ command | tojson }}
